In [2]:
import pandas as pd 
import sqlite3

In [3]:
files = pd.read_csv('/home/jack/projects/RiboSeqOrg-DataPortal/data/trips_files.csv')
studies = pd.read_csv('/home/jack/projects/RiboSeqOrg-DataPortal/data/trips_studies.csv')

In [4]:
files.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9
0,0,1,10,1,SRR1945002.shelf,N2_L4_ribo_rep1,riboseq,1,19142565.0,NaN,NaN
1,1,2,10,1,SRR1945003.shelf,N2_L4_ribo_rep2,riboseq,1,2510719.0,NaN,NaN
2,2,3,10,1,SRR1945004.shelf,tut_1_L4_ribo_rep1,riboseq,1,13790426.0,NaN,NaN
3,3,4,10,1,SRR1945005.shelf,tut_1_L4_ribo_rep2,riboseq,1,2718916.0,NaN,NaN
4,4,5,10,1,SRR1945008.shelf,tut_1_elpc_1_adult_mRNA_rep1,rnaseq,1,24901945.0,NaN,NaN

In [5]:
studies.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0,-1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,1,1,10,Nedialkova15,"Nedialkova DD, Leidel SA",SRP056647,2015,26052047,"""https://linkinghub.elsevier.com/retrieve/pii/...",GSE67387,NaN,Optimization of Codon Translation Rates via tR...,Ribosome profiling of wild-type and tRNA modif...,0,1
2,2,2,7,Dunn13,"Dunn JG, Foo CK, Belletier NG, Gavis ER, Weiss...",SRP028243,2013,24302569,"""https://doi.org/10.7554/eLife.01179""",GSE49197,CTGTAGGCACCATCAAT,Ribosome profiling reveals pervasive and regul...,12 samples of Drosophila ribosome profiling an...,0,1
3,3,3,8,Nakahigashi16,"Nakahigashi K, Takai Y, Kimura M, Abe N, Nakay...",DRP003075,2016,NaN,https://academic.oup.com/dnaresearch/article-l...,Nakahigashi16,NaN,Comprehensive identification of translation st...,NaN,0,1
4,4,4,8,Woolstenhulme15,"Woolstenhulme CJ, Guydosh NR, Green R, Buskirk AR",SRP051520,2015,25843707,"""https://linkinghub.elsevier.com/retrieve/pii/...",GSE64488,CTGTAGGCACCATCAAT,High-precision analysis of translational pausi...,Ribosome profiling of E. coli MG1655 and mutan...,0,1